version: "3.9"

services:
  api:
    build:
      context: ./api
    container_name: chat_api
    ports:
      - "9999:9999"
    command:
      "uvicorn app:app --host 0.0.0.0 --port 9999"
    restart: always


  bot:
    build:
      context: ./bot
    container_name: chat_bot
    environment:
          GET_STATUS: http://localhost:9999
          TELEGRAM_BOT_TOKEN: ${TELEGRAM_BOT_TOKEN}
    depends_on:
      - api
    tty: true
    stdin_open: true
    network_mode: host
    restart: always
    command:
      "python3 controll_bot.py"

  main:
    build:
      context: .
    container_name: chat_main
    environment:
      API_ID: ${API_ID}
      API_HASH: ${API_HASH}
      SESSION: ${SESSION}
      OPEN_API_KEY: ${OPEN_API_KEY}
      SMS_API_KEY: ${SMS_API_KEY}
      USERNAME_SMS: ${USERNAME_SMS}
    depends_on:
      - api
    network_mode: host
    tty: true
    stdin_open: true
    restart: always
    command:
      "python3 main.py"

